# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
