# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20170713_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to=''),
        ),
    ]
